### PR TITLE
Added From parameter to createNote function

### PR DESCRIPTION
**Pull request by Nnoromuche**
#107

### CODE REVIEW

**Comment by Nnoromuche** [comment]
When you want to create a note on an incident. The API Guide specifies that the user's email address should be passed as a parameter in the header using the "From" field. See https://v2.developer.pagerduty.com/v2/page/api-reference#!/Incidents/post_incidents_id_notes . However this is missing in the library, so I have updated the library to enable this.

**Comment by Nnoromuche** [comment]
Hi, pls could you review and merge @aantix @raganwald @rduffield @taavi @jolexa

**Comment by raganwald** [comment]
> Hi, pls could you review and merge @aantix @raganwald @rduffield @taavi @jolexa @mimato thanks

An easier way to request a review:

ez

:-)

**Comment by Nnoromuche** [comment]
@raganwald I tried that but it doesn't give me the option to request a reviewer. I think that option is access protected and only visible to your team

screen shot 2018-02-02 at 10 10 25

**Comment by mattstratton** [comment]
@Nnoromuche Can you rebase and update this PR, since there's now a conflict? I'll review it then. Sorry for the delay!

**Pull request merged**
