### PR TITLE
Add capability to update incidents

### PR DESCRIPTION
**Pull request by bendehaan**
Add a method and corresponding unit test for updating incidents.

### CODE REVIEW

**Comment by bendehaan** [comment]
I understood from support that currently updating incidents is not supported. Is that something you will support in the future?

**Comment by theckman** [comment]
@bendehaan could you share more about that context of updating not being supported? This documentation makes it seem like it is: https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents~1%7Bid%7D/put

Full disclosure while I do have merge access I am not an employee, so the context you heard would be helpful if you could share it.

**Comment by bendehaan** [comment]
@theckman Sure! I thought the same from documentation, but this is the message I got from PagerDuty tech support:
```
Hello Ben,

Thanks for reaching out. Once an Incident has been triggered, it can’t be updated. You would have to create a new alert and have this deduplicated or grouped into the incident to keep all the context in one place. But updating custom details ect within on Incident and Alert is not supported.

Kind regards, 
```

**Comment by theckman** [comment]
@bendehaan thank you for that context. Yeah, I'd say it's probably best to close the PR since it's not something their API is supporting today. I don't have a great way to know if they ever will support that, so I'll close this PR for now. But please reopen it if that API support is ever added.

**Pull request closed without merging**
