### PR TITLE
Add support for incident creation

### PR DESCRIPTION
**Pull request by luqasn**
The current version of the client does not allow creation of incidents for services. This PR changes that.

### CODE REVIEW

**Comment by sevagh** [comment]
Wouldn't the body be better as an `Incident` object? https://github.com/PagerDuty/go-pagerduty/compare/master...sevagh:master

I feel like that matches the API more: https://v2.developer.pagerduty.com/docs/incident-creation-api

Maybe I've misunderstood.

**Comment by luqasn** [comment]
I don’t understand what you mean, your and my changes look almost identical to me (though I only implemented support for title)

**Comment by sevagh** [comment]
Sorry about that, I did some force-pushes between my first message and now.

I added this: `EscalationPolicy APIReference `json:"escalation_policy,omitempty"`` so that I can alert on different escalation policies. Is there a way to do that from your change?

**Comment by sevagh** [comment]
This is how I use it:

```
createIncidentOptions := pagerduty.CreateIncidentOptions{
                Title: "oncall-bot-incident",
                Service: pagerduty.APIReference{
                        ID:   "XXXXXX",
                        Type: "service_reference",
                },
                EscalationPolicy: pagerduty.APIReference{
                        ID:   escalation.ID,
                        Type: "escalation_policy_reference",
                },
        }
```

**Comment by sevagh** [comment]
What do you think of adding the `EscalationPolicy` field?

```
+type CreateIncidentOptions struct {
+	APIObject
+	Title    string   `json:"title,omitempty"`
+        Service APIReference `json:"service,omitempty"`
+        EscalationPolicy APIReference `json:"escalation_policy,omitempty"`
+}
+```

This is how I'm using it in prod right now. https://v2.developer.pagerduty.com/docs/incident-creation-api#making-a-request

`EscalationPolicy` is one of the optional fields in the API spec. What do you think about adding it to your PR? Then I don't need to use my fork when your PR gets merged.

**Comment by luqasn** [comment]
Yeah, I think that's a good idea. Will try to get to that in the next days.

**Comment by luqasn** [comment]
I have added most of the other supported parameters, but a few are still missing, for example a detailed message body. This is good enough for my use case, but I think for completeness, I should add everything else as well.

**Comment by eldios** [comment]
I guess that this can be closed since the function has been already added, right @mattstratton @luqasn ?

**Comment by luqasn** [comment]
Yep, closing. Thanks for adding it.

**Pull request closed without merging**
