### PR TITLE
Create Incident, List Priorities, and headers in POST method support

### PR DESCRIPTION
**Pull request by ldelossa**
Submitting this PR which adds support for POSTing (creating) an incident along with GETing (listing) priorities in the new priorities feature. Willing to change around any struct naming or json construction logic at request. 

Methods added:

client.CreateIncidents
client.ListPriorities 

PR also plumbed header support into POST method on the client.

### CODE REVIEW

**Comment by wdhnl** [comment]
I think the method name should be CreateIncident not CreateIncidents since it creates a singular incident

The naming of the type to pass into the CreateIncident should be CreateIncidentOptions to match other method signatures

**Comment by wdhnl** [comment]
Since CreateIncidentResponse isn't returned anywhere (just used to unmarshal the response inside CreateIncident(s) ), should it be private?

(I struggled with same thing on my PR)

**Comment by ldelossa** [comment]
@wdhnl agree to both your comments, will update.

**Comment by wdhnl** [comment]
Will you have time to update this?

**Comment by ldelossa** [comment]
@wdhnl dunzo. sorry about that got side tracked.

**Comment by wdhnl** [comment]
@mattstratton can you evaluate this PR?

**Comment by ldelossa** [comment]
Hey Bill I just realized I missed one of the recommendations. Will fix
tonight or first thing tomorrow

**Comment by ldelossa** [comment]
@wdhnl renamed CreateIncidentValue to CreateIncidentOptions like suggested.

**Comment by wdhnl** [comment]
awseome, thanks

**Pull request merged**
