### PR TITLE
Change makefiles and readme

### PR DESCRIPTION
**Pull request by dineshba**
Tasks:
1) Introduce go mod
2) Update Makefile targets

### CODE REVIEW

**Comment by dineshba** [comment]
Fixes this issue also https://github.com/PagerDuty/go-pagerduty/issues/160

**Comment by dineshba** [comment]
Hi @stmcallister Made the changes to the PR. I am okay with `GO111MODULE` being auto.

**Comment by stmcallister** [comment]
Thanks, @dineshba! Also, any strong objections to adding the following lines to `.gitignore`?

```
vendor/
pd
```

**Comment by dineshba** [comment]
@stmcallister Added `pd` to gitignore. 

Can we check in `vendor` folder to `git` ? Advantage: Builds will be very fast in CI(as vendor is already present with code). Whats your opinion on this ?

**Comment by stmcallister** [comment]
@dineshba  We discussed this internally, and checking the `vendor` directory into the repo has pluses  and negatives. The build speed you mentioned would be nice, but the policing of dependencies would be  more tedious. Especially when developers can get the same benefit by running `go mod vendor`. So, we would rather not check the `vendor` directory into the repo, but instead either have devs run `go mod vendor` or include that in the makefile.

**Comment by dineshba** [comment]
@stmcallister I agree with you. Added `vendor/` to `.gitignore`. As you suggested, developers can still use `go mod vendor` and build using `vendor` directory. So i didn't modify `Makefile`

**Pull request merged**
