### PR TITLE
Add Support For Change Events

### PR DESCRIPTION
**Pull request by Sjeanpierre**
This PR implements the newly released [Change Events](https://developer.pagerduty.com/docs/events-api-v2/send-change-events/#try-it-out) feature. PR #241 seems to have taken a better approach on dealing with V2 Event endpoints in general, so if we can get some consensus on that approach I'd be more than happy to refactor that bit of my implementation.

### CODE REVIEW

**Comment by joelcrocker** [comment]
:+1: for the approach for dealing with events API endpoints from #241.

**Comment by Sjeanpierre** [comment]
Refactored to match the style from PR #241 should be good for review now @stmcallister

**Review by joelcrocker — APPROVED** [review]
:+1:

**Review by stmcallister — APPROVED** [review]
Great commenting and thanks for adding tests!

**Pull request merged**
